  - platform: template
    sensors:
      flaura1_charge_level:
        friendly_name: flaura1 charge level
        device_class: battery
        unit_of_measurement: "%"
		#e.g. (4.2-3)X100/(4.2-3) where 3 is the voltage at which esp turns off due to battery potection
        value_template: >
            {{ ((states('sensor.battery_level')|float-3) * 83.33)|round(2) }}Ba
